config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :posts
  get 'pages/home'
  root to: 'pages#home'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
    has_one_attached :image
    # has_many_attached :documents
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  def username
    return self.email.split('@')[0].capitalize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all.order(date: :desc) 
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:name, :description, :date, :image, )
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top ">

  <div class="container">
     <a class="navbar-brand order-1 mr-0" href="https://www.codethedream.org" target="_blank"> Presented by Code the Dream</a>
     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>   </button>

    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <% if current_user %>
        <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
        <% else %>
        <%= link_to 'Sign up', new_user_registration_path %>
        <%= link_to 'Sign in', new_user_session_path %>
        
        <%end%>

         <%# <a class="nav-item nav-link " href="#home"> Home <span class="sr-only">(current)</span></a> %>

         <a class="nav-item nav-link" href="#about">About</a>
         <li class='nav-item'><%= link_to 'Home', pages_home_path, class: 'nav-link' %></li>
          <li class='nav-item'><%= link_to 'Resources Access', orders_path, class: 'nav-link' %></li>
          <li class='nav-item'><%= link_to 'News and Announcements', posts_path, class: 'nav-link' %></li>



        <!-- <li class='nav-item'><#%= link_to 'Neighbors', customers_path, class: 'nav-link' %></li>
        <li class='nav-item'><#%= link_to 'Orders', orders_path, class: 'nav-link' %></li>

        <li class='nav-item'><#%= link_to 'Annual Fees', payments_path, class: 'nav-link' %></li> -->




    </div>
  </div>
</nav>

    <!--    navbar-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Evergreen Hoa Website" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Evergreen" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <header>
    <%= render 'layouts/navbar' %>
    </header>
    <main role="main">

    <%= render 'layouts/alerts' %>

    <%= yield %>
  </body>
</html>

app/views/orders/_form.html.erb
<%= simple_form_for(@order) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :date %>
  </div>

  <div class="field">
  <%= f.label :image %>
  <%= f.file_field :image, multiple: true%>
  </div>

  <div class="field">
  <%#= f.label :documents %>
  <%#= f.file_field :documents, multiple: true %>
  </div>
  
  <div class="form-actions">
    <%= f.button :submit %>
  </div>


  
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>



<h6> The HOA Board of Directors will review and approve your Application Form.</h6> 
<h6> Please Review the documents below and fill out the New Order Form, you can add an image if necessary to support your project </h6>


<p><%= link_to "Application Form", "/order_form.pdf", :target=> "_blank" %></p>
<p><%= link_to "HOA Covenants", "/hoa_covenants.pdf", :target=> "_blank" %></p>
<p><%= link_to "Architectural Form", "/arch_review.pdf", :target=> "_blank" %></p>

<%= link_to 'New Order', new_order_path %>


<% if current_user && current_user.admin%>
          <h1>Orders</h1>

          <table>
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Description</th>
                  <th>Date</th>
                  <th colspan="3"></th>
                </tr>
              </thead>

              <tbody>
                <% @orders.each do |order| %>
                    <tr>
                      <td><%= order.name %></td>
                      <td><%= order.description %></td>
                      <td><%= order.date %></td>
                      
                      <td><%= link_to 'Show', order %></td>
                      <td><%= link_to 'Edit', edit_order_path(order) %></td>
                      <td><%= link_to 'Delete', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                    </tr>
                  
              </tbody>
          </table>

              <% end %>
<% end %>

app/views/orders/new.html.erb
<h1>New Documents Order</h1>



<% if current_user %>
        <%= render 'form', order: @order %>
    <%else%>
        <p> Please Register or Login as a Resident  </p>
        <%= link_to 'Sign up', new_user_registration_path %>
        <%= link_to 'Sign in', new_user_session_path %>
    <%end%>



<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @order.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @order.description %>
</p>

<p>
  <strong>Date:</strong>
  <%= @order.date %>
</p>

<p>
<% if @order.image.attachment %>
<div style="width:400px; height:auto">
  <strong>Document Picture:</strong>
  <%= link_to image_tag(@order.image, style: "width:100%"), orders_path %>

</div>
<% end %>
</p>


<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Evergreen HOA</title>
  </head>
  <body>



    <!--    jumbotron -->
          <div class="jumbotron jumbotron-fluid bg-info text-white ">
              <div class="container text-sm-center pt-5">
                <h3 class="display-4 ">Evergreen HOA  </h3>
                <h3 class="display-5">Cary, North Carolina </h3>
                <h4 class="display-2">Welcome! </h4>
                <%= link_to 'Register as a New Neighbor', new_user_registration_path, class: "btn btn-light btn-lg text-black nav-link"  %>
              </div>
          </div>

    <!--  /  jumbotron -->

<div class="container pt-4">

    <!-- about-->
        <div id="about"class="row">
            <div class="col-lg order-lg-2">
                  <h3 class="mb-4 text-muted">About Evergreen Community</h3>
                  <img class="mb-4 rounded img-fluid d-none d-sm-block" <%= image_tag("Test House.jpeg", border: 0) %>
                  <p>Evergreen HOA represents the interests of property owners in the Evergreen neighborhood. The HOA is a voluntary participation organization that supports  neighborhood initiatives with policies and best practices, functional committees and social activities with the stated objectives of enhancing security, growing community, and increasing property values.</p>
            </div>
            <div class="col-lg order-lg-1">
                  <h3 class="mb-4 text-muted" >Evergreen HOA Regulations</h3>
                  <p>Be considerate of common areas.</p>
                  <p>Pay attention to pets</p>
                  <p>Keep noise levels down..</p>
                  <p>Pay your homeowners association fees. Living in a homeowners association community means that you are required to pay monthly fees to be a part of it.</p>
                   
            </div>
            <div class="col-lg order-lg-3">
                <h3 class="mb-4 text-muted">Neighbohood Info</h3>
                  <div class="list-group">
                    <a href="https://www.townofcary.org/" class="list-group-item list-group-item-action"><strong>Cary Town</strong>: Local and updated information </a>
                    <a href="https://www.greatschools.org/north-carolina/cary/7674-Laurel-Park-Elementary/" class="list-group-item list-group-item-action"><strong>Elementary School</strong>: Laurel Park Elementary</a>
                    <a href="https://www.greatschools.org/north-carolina/apex/3367-Salem-Middle/" class="list-group-item list-group-item-action"><strong>Middle School</strong>: Salem Middle</a>
                    <a href="https://www.greatschools.org/north-carolina/cary/1907-Cary-High/" class="list-group-item list-group-item-action"><strong>High School</strong>: Cary High</a>
                  </div>
            </div>
        </div>
    <!-- /about-->

  <!--     Resident Access-->
  <section id="registration">
       <h3> Resident Access </h3>

        <%# <% if current_user %>
        <%#= link_to 'Sign out', destroy_user_session_path, method: :delete %>
        <%# <% else %>
        <%= link_to 'Sign up', new_user_registration_path %>
        <%= link_to 'Sign in', new_user_session_path %>
        <%# <%end%>

  <!--   /Resident Access-->
</section>


    <!--      blog-->

  

      <a  class="btn btn-outline-info btn-lg btn-block  text-black text-center" <%= link_to ' Share News and Events with your Neighbors!', new_post_path, class: 'nav-link'%></a>
      <h1 id="blog" class="display-5 text-center my-5 text-muted">Evergreen News and Events </h1>
      <%# <a class="list-group-item list-group-item-action active" data-toggle="list" href="#posts" role="tab">Home</a> %>


      <div class="card">
      <div class="card-header">
      <center> <h3>July Newsletter</h3></center>
          </div>
          <div class="card-body" >
          <center>
              <h5 class="card-title">Comitee Meeting in July</h5>
              <p class="card-text"><p>Check the las Updates on Covid19 cases in our area!</p>
              <a href="#" class="btn btn-primary">Show More</a>
          </center>
      </div>
    </div>
  <br>

  <div class="card">
  <div class="card-header">
  <center><h3>June Newsletter</h3></center>
  </div>
  <div class="card-body">
    <center>
      <h5 class="card-title">New payment online. Available soon!!!</h5>
      <p class="card-text">Check how to pay online from our website!</p>
      <a href="#" class="btn btn-primary">Show More</a>
    </center>
  </div>
</div>
<br>

<div class="row">
    <div class="col-sm-6">
      <div class="card" style="width: 18rem;">
        <%= image_tag("tuka.jpeg", border: 0) %>
        <div class="card-body">
          <p class="card-text"><h5>Los Pet!!! Name: "Lazy", House: 109 London Plain ct, last seen Friday afternoon</h5>
          <a href="#" class="btn btn-primary">Show More</a>
       </div>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="card" style="width: 18rem;">
        <%= image_tag("landscaping.jpeg", border: 0) %>
        <div class="card-body">
          <p class="card-text"><h5>Decorate your front door with a white tie! Showing Support for our Covid-19 heroes. Close to a tree or front porch.</h5>
        <a href="#" class="btn btn-primary">Show More</a>
      </div>
    </div>
    
</div>








<!--   /   blog-->




</div><!-- /.container-->

<% #<div class="container pt-5"> %>

      <!--     footer-->

        <div class="row py-3">
          <div class="col-md-7">

              <h3 class="mb-1">Contact us: </h3>
              <h6><strong>Email:</strong><a href="mailto: evergreenhoaofcary@gmail.com?subject=Hi%20Evergreen!">evergreenhoaofcary@gmail.com </a></h6>
              <h6 class="mb-1">Mailing address:</h6>
              <h6 class="mb-1">Evergreen Homeowners Association</h6>
              <h6 class="mb-1">17xx Cary Parkway Drive, Ste 1xx </h6>
              <h6 class="mb-1">17xx Cary,  North Carolina  </h5> </h6>

          </div>
          </div>  <!-- /.container-->
        <div class="col-md text-md-right">
          <small>&copy; 2020 Evergreen HOA Website by Code the Dream</small>
        </div>
      <!--     /footer-->

</body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :body %>
   
  <%#= f.association :user %> 
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
<img class="mb-4  rounded img-fluid  max-width: 100% height: auto " <%= image_tag("jumbobanner.jpeg", border: 0) %>
<h2>Newsletter:</h2>

  <tbody>
    <% @posts.each do |post| %>
      <div class="container pt-2">

            <h4 class="mb-2 ">News Title: <%= post.title %></h4>
            <h4 class="mb-2 text-muted"><%= post.body %></h4>
           

            <td><%= link_to 'Show', post %></td>
            <% if current_user && current_user.admin%>
                  <td><%= link_to 'Edit', edit_post_path(post) %></td>
                  <td><%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>

      </div>
  <% end %>
  </tbody>




<%= link_to 'New Post', new_post_path %>
<li class='nav-item'><%= link_to 'Home', pages_home_path, class: 'nav-link' %></li>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>


<%# <p>
  <strong>User:</strong>
  <%= @post.user %>
</p> 

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>